name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        flags: ['', '-DSPI_HARD']
      fail-fast: false
    name: Arduino Nano ${{ matrix.flags }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v7
    - uses: arduino/setup-arduino-cli@v2
    - run: arduino-cli core update-index
    - run: arduino-cli core install arduino:avr
    - run: arduino-cli compile --fqbn arduino:avr:nano --build-property compiler.cpp.extra_flags="${{ matrix.flags }}" .